name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - working-directory: ./spring-gumball
      run: |
        chmod +x gradlew
        ./gradlew build
        ls build/libs

    - uses: actions/upload-artifact@v2.2.3
      with:
        name: spring-gumball
        path: spring-gumball/build/libs/spring-gumball-2.0.jar
